// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  configKey: __t.string().primaryKey().name("config_key"),
  geminiApiKey: __t.string().name("gemini_api_key"),
  apifreellmApiKey: __t.string().name("apifreellm_api_key"),
  scopusApiKey: __t.string().name("scopus_api_key"),
  orcidClientId: __t.string().name("orcid_client_id"),
  orcidClientSecret: __t.string().name("orcid_client_secret"),
  aiProvider: __t.string().name("ai_provider"),
  aiModel: __t.string().name("ai_model"),
  updatedAt: __t.timestamp().name("updated_at"),
});
