// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  publicationTitle: __t.string().name("publication_title"),
  quartile: __t.string(),
  publicationYear: __t.string().name("publication_year"),
  publicationType: __t.string().name("publication_type"),
  authorsCount: __t.u32().name("authors_count"),
  sourceKind: __t.string().name("source_kind"),
});
