// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  trackingId: __t.string().primaryKey().name("tracking_id"),
  professorName: __t.string().name("professor_name"),
  documentNumber: __t.string().name("document_number"),
  campus: __t.string(),
  programName: __t.string().name("program_name"),
  facultyName: __t.string().name("faculty_name"),
  scopusProfile: __t.option(__t.string()).name("scopus_profile"),
  status: __t.string(),
  outputMessage: __t.string().name("output_message"),
  finalPoints: __t.f64().name("final_points"),
  finalCategory: __t.string().name("final_category"),
  sourcePortal: __t.string().name("source_portal"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
