// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  actorUsername: __t.string().name("actor_username"),
  actorRole: __t.string().name("actor_role"),
  eventType: __t.string().name("event_type"),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
