// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  configKey: __t.string().primaryKey().name("config_key"),
  enabled: __t.bool(),
  bucketName: __t.string().name("bucket_name"),
  retrievalTopK: __t.u32().name("retrieval_top_k"),
  chunkSize: __t.u32().name("chunk_size"),
  chunkOverlap: __t.u32().name("chunk_overlap"),
  selectedProvider: __t.string().name("selected_provider"),
  selectedModel: __t.string().name("selected_model"),
  fallbackProvider: __t.string().name("fallback_provider"),
  fallbackModel: __t.string().name("fallback_model"),
  systemContext: __t.string().name("system_context"),
  updatedAt: __t.timestamp().name("updated_at"),
});
