// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  documentKey: __t.string().primaryKey().name("document_key"),
  fileName: __t.string().name("file_name"),
  fileType: __t.string().name("file_type"),
  fileSizeBytes: __t.u64().name("file_size_bytes"),
  bucketName: __t.string().name("bucket_name"),
  storagePath: __t.string().name("storage_path"),
  contentBase64: __t.option(__t.string()).name("content_base_64"),
  active: __t.bool(),
  uploadedBy: __t.option(__t.string()).name("uploaded_by"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
