// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  currentStatus: __t.string(),
  titleValidated: __t.bool(),
  experienceCertified: __t.bool(),
  publicationVerified: __t.bool(),
  languageValidated: __t.bool(),
  observations: __t.string(),
};
