// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  configKey: __t.string(),
  geminiApiKey: __t.string(),
  apifreellmApiKey: __t.string(),
  scopusApiKey: __t.string(),
  orcidClientId: __t.string(),
  orcidClientSecret: __t.string(),
  aiProvider: __t.string(),
  aiModel: __t.string(),
};
