// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  documentKey: __t.string(),
  fileName: __t.string(),
  fileType: __t.string(),
  fileSizeBytes: __t.u64(),
  bucketName: __t.string(),
  storagePath: __t.string(),
  contentBase64: __t.option(__t.string()),
  active: __t.bool(),
};
