// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  configKey: __t.string(),
  enabled: __t.bool(),
  bucketName: __t.string(),
  retrievalTopK: __t.u32(),
  chunkSize: __t.u32(),
  chunkOverlap: __t.u32(),
  selectedProvider: __t.string(),
  selectedModel: __t.string(),
  fallbackProvider: __t.string(),
  fallbackModel: __t.string(),
  systemContext: __t.string(),
};
