// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddApplicationExperienceReducer from "../add_application_experience_reducer";
import AddApplicationLanguageReducer from "../add_application_language_reducer";
import AddApplicationPublicationReducer from "../add_application_publication_reducer";
import AddApplicationTitleReducer from "../add_application_title_reducer";
import BootstrapFirstAdminReducer from "../bootstrap_first_admin_reducer";
import CreatePortalUserReducer from "../create_portal_user_reducer";
import CreateReportSnapshotReducer from "../create_report_snapshot_reducer";
import DeactivateRagDocumentReducer from "../deactivate_rag_document_reducer";
import InitPortalRolesReducer from "../init_portal_roles_reducer";
import PortalLoginReducer from "../portal_login_reducer";
import PortalLogoutReducer from "../portal_logout_reducer";
import RecordApplicationAuditReducer from "../record_application_audit_reducer";
import RegisterProfessorReducer from "../register_professor_reducer";
import RegisterUserProfileReducer from "../register_user_profile_reducer";
import UpdateApplicationStatusReducer from "../update_application_status_reducer";
import UpsertApiConfigReducer from "../upsert_api_config_reducer";
import UpsertEmailTemplateReducer from "../upsert_email_template_reducer";
import UpsertPortalRoleReducer from "../upsert_portal_role_reducer";
import UpsertRagConfigReducer from "../upsert_rag_config_reducer";
import UpsertRagDocumentReducer from "../upsert_rag_document_reducer";
import UpsertResendConfigReducer from "../upsert_resend_config_reducer";
import UpsertSystemSettingReducer from "../upsert_system_setting_reducer";

export type AddApplicationExperienceParams = __Infer<typeof AddApplicationExperienceReducer>;
export type AddApplicationLanguageParams = __Infer<typeof AddApplicationLanguageReducer>;
export type AddApplicationPublicationParams = __Infer<typeof AddApplicationPublicationReducer>;
export type AddApplicationTitleParams = __Infer<typeof AddApplicationTitleReducer>;
export type BootstrapFirstAdminParams = __Infer<typeof BootstrapFirstAdminReducer>;
export type CreatePortalUserParams = __Infer<typeof CreatePortalUserReducer>;
export type CreateReportSnapshotParams = __Infer<typeof CreateReportSnapshotReducer>;
export type DeactivateRagDocumentParams = __Infer<typeof DeactivateRagDocumentReducer>;
export type InitPortalRolesParams = __Infer<typeof InitPortalRolesReducer>;
export type PortalLoginParams = __Infer<typeof PortalLoginReducer>;
export type PortalLogoutParams = __Infer<typeof PortalLogoutReducer>;
export type RecordApplicationAuditParams = __Infer<typeof RecordApplicationAuditReducer>;
export type RegisterProfessorParams = __Infer<typeof RegisterProfessorReducer>;
export type RegisterUserProfileParams = __Infer<typeof RegisterUserProfileReducer>;
export type UpdateApplicationStatusParams = __Infer<typeof UpdateApplicationStatusReducer>;
export type UpsertApiConfigParams = __Infer<typeof UpsertApiConfigReducer>;
export type UpsertEmailTemplateParams = __Infer<typeof UpsertEmailTemplateReducer>;
export type UpsertPortalRoleParams = __Infer<typeof UpsertPortalRoleReducer>;
export type UpsertRagConfigParams = __Infer<typeof UpsertRagConfigReducer>;
export type UpsertRagDocumentParams = __Infer<typeof UpsertRagDocumentReducer>;
export type UpsertResendConfigParams = __Infer<typeof UpsertResendConfigReducer>;
export type UpsertSystemSettingParams = __Infer<typeof UpsertSystemSettingReducer>;

