// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  titleName: __t.string(),
  titleLevel: __t.string(),
  graduationDate: __t.option(__t.string()),
  originUniversity: __t.option(__t.string()),
  universityType: __t.option(__t.string()),
  titleConvalidated: __t.option(__t.bool()),
  convalidationSupportName: __t.option(__t.string()),
  convalidationSupportPath: __t.option(__t.string()),
  supportName: __t.option(__t.string()),
  supportUrl: __t.option(__t.string()),
  supportPath: __t.option(__t.string()),
};
