// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  experienceType: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
  certified: __t.bool(),
  supportName: __t.option(__t.string()),
  supportUrl: __t.option(__t.string()),
  supportPath: __t.option(__t.string()),
};
