// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  titleName: __t.string().name("title_name"),
  titleLevel: __t.string().name("title_level"),
  supportName: __t.option(__t.string()).name("support_name"),
  supportUrl: __t.option(__t.string()).name("support_url"),
  supportPath: __t.option(__t.string()).name("support_path"),
  graduationDate: __t.string().name("graduation_date"),
  originUniversity: __t.string().name("origin_university"),
  universityType: __t.string().name("university_type"),
  titleConvalidated: __t.bool().name("title_convalidated"),
  convalidationSupportName: __t.string().name("convalidation_support_name"),
  convalidationSupportPath: __t.string().name("convalidation_support_path"),
});
