// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  criterionId: __t.string().primaryKey().name("criterion_id"),
  trackingId: __t.string().name("tracking_id"),
  criterionKey: __t.string().name("criterion_key"),
  criterionLabel: __t.string().name("criterion_label"),
  criterionStatus: __t.string().name("criterion_status"),
  quantity: __t.f64(),
  unitLabel: __t.string().name("unit_label"),
  baseWeight: __t.f64().name("base_weight"),
  recommendedScore: __t.f64().name("recommended_score"),
  weightedScore: __t.f64().name("weighted_score"),
  supportSummary: __t.string().name("support_summary"),
  notes: __t.string(),
  reviewerUsername: __t.option(__t.string()).name("reviewer_username"),
  valuationStage: __t.string().name("valuation_stage"),
  updatedAt: __t.timestamp().name("updated_at"),
});
