// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  trackingId: __t.string().primaryKey().name("tracking_id"),
  currentStatus: __t.string().name("current_status"),
  titleValidated: __t.bool().name("title_validated"),
  experienceCertified: __t.bool().name("experience_certified"),
  publicationVerified: __t.bool().name("publication_verified"),
  languageValidated: __t.bool().name("language_validated"),
  observations: __t.string(),
  reviewerUsername: __t.option(__t.string()).name("reviewer_username"),
  updatedAt: __t.timestamp().name("updated_at"),
});
