// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  experienceType: __t.string().name("experience_type"),
  startedAt: __t.string().name("started_at"),
  endedAt: __t.string().name("ended_at"),
  certified: __t.bool(),
  supportName: __t.option(__t.string()).name("support_name"),
  supportUrl: __t.option(__t.string()).name("support_url"),
  supportPath: __t.option(__t.string()).name("support_path"),
});
