// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  documentId: __t.string().primaryKey().name("document_id"),
  trackingId: __t.string().name("tracking_id"),
  documentType: __t.string().name("document_type"),
  fileName: __t.string().name("file_name"),
  fileUrl: __t.option(__t.string()).name("file_url"),
  filePath: __t.option(__t.string()).name("file_path"),
  uploadedBy: __t.option(__t.string()).name("uploaded_by"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
});
