// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  versionId: __t.string().primaryKey().name("version_id"),
  trackingId: __t.string().name("tracking_id"),
  sourceType: __t.string().name("source_type"),
  versionStatus: __t.string().name("version_status"),
  rowsPayload: __t.string().name("rows_payload"),
  totalScore: __t.f64().name("total_score"),
  suggestedCategory: __t.string().name("suggested_category"),
  narrative: __t.string(),
  notes: __t.string(),
  createdBy: __t.option(__t.string()).name("created_by"),
  createdRole: __t.option(__t.string()).name("created_role"),
  approvedBy: __t.option(__t.string()).name("approved_by"),
  approvedAt: __t.option(__t.timestamp()).name("approved_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
