// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  valuationStage: __t.string().name("valuation_stage"),
  actorUsername: __t.string().name("actor_username"),
  actorRole: __t.string().name("actor_role"),
  suggestedScore: __t.f64().name("suggested_score"),
  currentWeightedScore: __t.f64().name("current_weighted_score"),
  finalWeightedScore: __t.option(__t.f64()).name("final_weighted_score"),
  finalCategory: __t.option(__t.string()).name("final_category"),
  notes: __t.string(),
  criteriaCount: __t.u32().name("criteria_count"),
  createdAt: __t.timestamp().name("created_at"),
});
