// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  trackingId: __t.string().name("tracking_id"),
  criterionKey: __t.string().name("criterion_key"),
  valuationStage: __t.string().name("valuation_stage"),
  actorUsername: __t.string().name("actor_username"),
  actorRole: __t.string().name("actor_role"),
  previousStatus: __t.option(__t.string()).name("previous_status"),
  newStatus: __t.string().name("new_status"),
  previousBaseWeight: __t.option(__t.f64()).name("previous_base_weight"),
  newBaseWeight: __t.f64().name("new_base_weight"),
  previousRecommendedScore: __t.option(__t.f64()).name("previous_recommended_score"),
  newRecommendedScore: __t.f64().name("new_recommended_score"),
  previousWeightedScore: __t.option(__t.f64()).name("previous_weighted_score"),
  newWeightedScore: __t.f64().name("new_weighted_score"),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
