// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  codigo: __t.string(),
  nombre: __t.string(),
  descripcion: __t.string(),
  periodo: __t.string(),
  año: __t.u32(),
  fechaApertura: __t.string().name("fecha_apertura"),
  fechaCierre: __t.string().name("fecha_cierre"),
  estado: __t.string(),
  postulacionesCount: __t.u32().name("postulaciones_count"),
  createdBy: __t.option(__t.string()).name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
