// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  codigo: __t.string(),
  nombre: __t.string(),
  descripcion: __t.string(),
  periodo: __t.string(),
  año: __t.u32(),
  fechaApertura: __t.string(),
  fechaCierre: __t.string(),
  estado: __t.string(),
};
