// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  trackingId: __t.string().primaryKey().name("tracking_id"),
  category: __t.string(),
  iesName: __t.string().name("ies_name"),
  certificationName: __t.option(__t.string()).name("certification_name"),
  certificationPath: __t.option(__t.string()).name("certification_path"),
  certificationUrl: __t.option(__t.string()).name("certification_url"),
  createdBy: __t.option(__t.string()).name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
