// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  trackingId: __t.string().primaryKey().name("tracking_id"),
  htmlContent: __t.string().name("html_content"),
  narrativeJson: __t.string().name("narrative_json"),
  aiProvider: __t.string().name("ai_provider"),
  aiModel: __t.string().name("ai_model"),
  generatedBy: __t.option(__t.string()).name("generated_by"),
  generatedAt: __t.timestamp().name("generated_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
