// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  role: __t.string(),
  displayName: __t.string().name("display_name"),
  active: __t.bool(),
  loggedInAt: __t.timestamp().name("logged_in_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
