// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  normativeKey: __t.string().primaryKey().name("normative_key"),
  title: __t.string(),
  documentId: __t.string().name("document_id"),
  jsonContent: __t.string().name("json_content"),
  bucketName: __t.string().name("bucket_name"),
  storagePath: __t.string().name("storage_path"),
  active: __t.bool(),
  uploadedBy: __t.option(__t.string()).name("uploaded_by"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
