// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  reviewStatus: __t.string(),
  observations: __t.option(__t.string()),
  interviewFileName: __t.option(__t.string()),
  interviewFileUrl: __t.option(__t.string()),
  interviewFilePath: __t.option(__t.string()),
  decisionFileName: __t.option(__t.string()),
  decisionFileUrl: __t.option(__t.string()),
  decisionFilePath: __t.option(__t.string()),
};
