// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  professorName: __t.string(),
  documentNumber: __t.string(),
  campus: __t.string(),
  programName: __t.string(),
  facultyName: __t.string(),
  convocatoriaId: __t.option(__t.string()),
  scopusProfile: __t.option(__t.string()),
  finalPoints: __t.f64(),
  finalCategory: __t.string(),
  outputMessage: __t.string(),
};
