// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApiConfig = __t.object("ApiConfig", {
  configKey: __t.string(),
  geminiApiKey: __t.string(),
  apifreellmApiKey: __t.string(),
  scopusApiKey: __t.string(),
  orcidClientId: __t.string(),
  orcidClientSecret: __t.string(),
  aiProvider: __t.string(),
  aiModel: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ApiConfig = __Infer<typeof ApiConfig>;

export const Application = __t.object("Application", {
  trackingId: __t.string(),
  professorName: __t.string(),
  documentNumber: __t.string(),
  campus: __t.string(),
  programName: __t.string(),
  facultyName: __t.string(),
  scopusProfile: __t.option(__t.string()),
  status: __t.string(),
  outputMessage: __t.string(),
  finalPoints: __t.f64(),
  finalCategory: __t.string(),
  sourcePortal: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Application = __Infer<typeof Application>;

export const ApplicationAudit = __t.object("ApplicationAudit", {
  trackingId: __t.string(),
  currentStatus: __t.string(),
  titleValidated: __t.bool(),
  experienceCertified: __t.bool(),
  publicationVerified: __t.bool(),
  languageValidated: __t.bool(),
  observations: __t.string(),
  reviewerUsername: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type ApplicationAudit = __Infer<typeof ApplicationAudit>;

export const ApplicationExperience = __t.object("ApplicationExperience", {
  id: __t.u32(),
  trackingId: __t.string(),
  experienceType: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
  certified: __t.bool(),
  supportName: __t.option(__t.string()),
  supportUrl: __t.option(__t.string()),
  supportPath: __t.option(__t.string()),
});
export type ApplicationExperience = __Infer<typeof ApplicationExperience>;

export const ApplicationLanguage = __t.object("ApplicationLanguage", {
  id: __t.u32(),
  trackingId: __t.string(),
  languageName: __t.string(),
  languageLevel: __t.string(),
  convalidation: __t.bool(),
});
export type ApplicationLanguage = __Infer<typeof ApplicationLanguage>;

export const ApplicationPublication = __t.object("ApplicationPublication", {
  id: __t.u32(),
  trackingId: __t.string(),
  publicationTitle: __t.string(),
  quartile: __t.string(),
  publicationYear: __t.string(),
  publicationType: __t.string(),
  authorsCount: __t.u32(),
  sourceKind: __t.string(),
});
export type ApplicationPublication = __Infer<typeof ApplicationPublication>;

export const ApplicationTitle = __t.object("ApplicationTitle", {
  id: __t.u32(),
  trackingId: __t.string(),
  titleName: __t.string(),
  titleLevel: __t.string(),
  supportName: __t.option(__t.string()),
  supportUrl: __t.option(__t.string()),
  supportPath: __t.option(__t.string()),
});
export type ApplicationTitle = __Infer<typeof ApplicationTitle>;

export const AuditEvent = __t.object("AuditEvent", {
  id: __t.u32(),
  trackingId: __t.string(),
  actorUsername: __t.string(),
  actorRole: __t.string(),
  eventType: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const EmailTemplate = __t.object("EmailTemplate", {
  templateKey: __t.string(),
  workflowKey: __t.string(),
  subject: __t.string(),
  htmlContent: __t.string(),
  enabled: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type EmailTemplate = __Infer<typeof EmailTemplate>;

export const PortalRole = __t.object("PortalRole", {
  roleKey: __t.string(),
  roleName: __t.string(),
  portalModule: __t.string(),
  description: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PortalRole = __Infer<typeof PortalRole>;

export const PortalSession = __t.object("PortalSession", {
  identity: __t.identity(),
  username: __t.string(),
  role: __t.string(),
  displayName: __t.string(),
  active: __t.bool(),
  loggedInAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type PortalSession = __Infer<typeof PortalSession>;

export const PortalUser = __t.object("PortalUser", {
  id: __t.u32(),
  username: __t.string(),
  password: __t.string(),
  role: __t.string(),
  displayName: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type PortalUser = __Infer<typeof PortalUser>;

export const RagConfig = __t.object("RagConfig", {
  configKey: __t.string(),
  enabled: __t.bool(),
  bucketName: __t.string(),
  retrievalTopK: __t.u32(),
  chunkSize: __t.u32(),
  chunkOverlap: __t.u32(),
  selectedProvider: __t.string(),
  selectedModel: __t.string(),
  fallbackProvider: __t.string(),
  fallbackModel: __t.string(),
  systemContext: __t.string(),
  updatedAt: __t.timestamp(),
});
export type RagConfig = __Infer<typeof RagConfig>;

export const RagDocument = __t.object("RagDocument", {
  documentKey: __t.string(),
  fileName: __t.string(),
  fileType: __t.string(),
  fileSizeBytes: __t.u64(),
  bucketName: __t.string(),
  storagePath: __t.string(),
  contentBase64: __t.option(__t.string()),
  active: __t.bool(),
  uploadedBy: __t.option(__t.string()),
  uploadedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RagDocument = __Infer<typeof RagDocument>;

export const ReportSnapshot = __t.object("ReportSnapshot", {
  id: __t.u32(),
  campus: __t.string(),
  metricKey: __t.string(),
  metricValue: __t.f64(),
  periodLabel: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReportSnapshot = __Infer<typeof ReportSnapshot>;

export const ResendConfig = __t.object("ResendConfig", {
  configKey: __t.string(),
  apiKey: __t.string(),
  fromEmail: __t.string(),
  fromName: __t.string(),
  enabled: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type ResendConfig = __Infer<typeof ResendConfig>;

export const SystemSetting = __t.object("SystemSetting", {
  key: __t.string(),
  scope: __t.string(),
  campus: __t.option(__t.string()),
  value: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SystemSetting = __Infer<typeof SystemSetting>;

export const UserProfile = __t.object("UserProfile", {
  id: __t.u32(),
  nombre: __t.string(),
  correo: __t.string(),
  campus: __t.string(),
  password: __t.string(),
  role: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

