// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  correo: __t.string(),
  nombre: __t.option(__t.string()),
  campus: __t.option(__t.string()),
  role: __t.option(__t.string()),
  active: __t.option(__t.bool()),
  facultyId: __t.option(__t.string()),
};
