// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trackingId: __t.string(),
  category: __t.string(),
  iesName: __t.string(),
  certificationName: __t.option(__t.string()),
  certificationPath: __t.option(__t.string()),
  certificationUrl: __t.option(__t.string()),
};
