// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddApplicationExperienceReducer from "../add_application_experience_reducer";
import AddApplicationLanguageReducer from "../add_application_language_reducer";
import AddApplicationPublicationReducer from "../add_application_publication_reducer";
import AddApplicationTitleReducer from "../add_application_title_reducer";
import ApproveApplicationAnalysisVersionReducer from "../approve_application_analysis_version_reducer";
import BootstrapFirstAdminReducer from "../bootstrap_first_admin_reducer";
import CloseConvocatoriaReducer from "../close_convocatoria_reducer";
import CreateConvocatoriaReducer from "../create_convocatoria_reducer";
import CreatePortalUserReducer from "../create_portal_user_reducer";
import CreateReportSnapshotReducer from "../create_report_snapshot_reducer";
import DeactivateRagDocumentReducer from "../deactivate_rag_document_reducer";
import DeactivateRagNormativeReducer from "../deactivate_rag_normative_reducer";
import ImportFacultyProgramsReducer from "../import_faculty_programs_reducer";
import InitPortalRolesReducer from "../init_portal_roles_reducer";
import LinkApplicationConvocatoriaReducer from "../link_application_convocatoria_reducer";
import PortalLoginReducer from "../portal_login_reducer";
import PortalLogoutReducer from "../portal_logout_reducer";
import RecordApplicationAuditReducer from "../record_application_audit_reducer";
import RecordDecanoReviewReducer from "../record_decano_review_reducer";
import RegisterProfessorReducer from "../register_professor_reducer";
import RegisterUserProfileReducer from "../register_user_profile_reducer";
import SaveApplicationAnalysisVersionReducer from "../save_application_analysis_version_reducer";
import UpdateApplicationExperienceSupportReducer from "../update_application_experience_support_reducer";
import UpdateApplicationPublicationSourceKindReducer from "../update_application_publication_source_kind_reducer";
import UpdateApplicationStatusReducer from "../update_application_status_reducer";
import UpdateApplicationTitleSupportReducer from "../update_application_title_support_reducer";
import UpdateConvocatoriaReducer from "../update_convocatoria_reducer";
import UpdateUserProfileReducer from "../update_user_profile_reducer";
import UpsertAcademicProgramReducer from "../upsert_academic_program_reducer";
import UpsertApiConfigReducer from "../upsert_api_config_reducer";
import UpsertEmailTemplateReducer from "../upsert_email_template_reducer";
import UpsertFacultyReducer from "../upsert_faculty_reducer";
import UpsertOpenrouterConfigReducer from "../upsert_openrouter_config_reducer";
import UpsertPortalRoleReducer from "../upsert_portal_role_reducer";
import UpsertRagConfigReducer from "../upsert_rag_config_reducer";
import UpsertRagDocumentReducer from "../upsert_rag_document_reducer";
import UpsertRagNormativeReducer from "../upsert_rag_normative_reducer";
import UpsertResendConfigReducer from "../upsert_resend_config_reducer";
import UpsertSystemSettingReducer from "../upsert_system_setting_reducer";

export type AddApplicationExperienceParams = __Infer<typeof AddApplicationExperienceReducer>;
export type AddApplicationLanguageParams = __Infer<typeof AddApplicationLanguageReducer>;
export type AddApplicationPublicationParams = __Infer<typeof AddApplicationPublicationReducer>;
export type AddApplicationTitleParams = __Infer<typeof AddApplicationTitleReducer>;
export type ApproveApplicationAnalysisVersionParams = __Infer<typeof ApproveApplicationAnalysisVersionReducer>;
export type BootstrapFirstAdminParams = __Infer<typeof BootstrapFirstAdminReducer>;
export type CloseConvocatoriaParams = __Infer<typeof CloseConvocatoriaReducer>;
export type CreateConvocatoriaParams = __Infer<typeof CreateConvocatoriaReducer>;
export type CreatePortalUserParams = __Infer<typeof CreatePortalUserReducer>;
export type CreateReportSnapshotParams = __Infer<typeof CreateReportSnapshotReducer>;
export type DeactivateRagDocumentParams = __Infer<typeof DeactivateRagDocumentReducer>;
export type DeactivateRagNormativeParams = __Infer<typeof DeactivateRagNormativeReducer>;
export type ImportFacultyProgramsParams = __Infer<typeof ImportFacultyProgramsReducer>;
export type InitPortalRolesParams = __Infer<typeof InitPortalRolesReducer>;
export type LinkApplicationConvocatoriaParams = __Infer<typeof LinkApplicationConvocatoriaReducer>;
export type PortalLoginParams = __Infer<typeof PortalLoginReducer>;
export type PortalLogoutParams = __Infer<typeof PortalLogoutReducer>;
export type RecordApplicationAuditParams = __Infer<typeof RecordApplicationAuditReducer>;
export type RecordDecanoReviewParams = __Infer<typeof RecordDecanoReviewReducer>;
export type RegisterProfessorParams = __Infer<typeof RegisterProfessorReducer>;
export type RegisterUserProfileParams = __Infer<typeof RegisterUserProfileReducer>;
export type SaveApplicationAnalysisVersionParams = __Infer<typeof SaveApplicationAnalysisVersionReducer>;
export type UpdateApplicationExperienceSupportParams = __Infer<typeof UpdateApplicationExperienceSupportReducer>;
export type UpdateApplicationPublicationSourceKindParams = __Infer<typeof UpdateApplicationPublicationSourceKindReducer>;
export type UpdateApplicationStatusParams = __Infer<typeof UpdateApplicationStatusReducer>;
export type UpdateApplicationTitleSupportParams = __Infer<typeof UpdateApplicationTitleSupportReducer>;
export type UpdateConvocatoriaParams = __Infer<typeof UpdateConvocatoriaReducer>;
export type UpdateUserProfileParams = __Infer<typeof UpdateUserProfileReducer>;
export type UpsertAcademicProgramParams = __Infer<typeof UpsertAcademicProgramReducer>;
export type UpsertApiConfigParams = __Infer<typeof UpsertApiConfigReducer>;
export type UpsertEmailTemplateParams = __Infer<typeof UpsertEmailTemplateReducer>;
export type UpsertFacultyParams = __Infer<typeof UpsertFacultyReducer>;
export type UpsertOpenrouterConfigParams = __Infer<typeof UpsertOpenrouterConfigReducer>;
export type UpsertPortalRoleParams = __Infer<typeof UpsertPortalRoleReducer>;
export type UpsertRagConfigParams = __Infer<typeof UpsertRagConfigReducer>;
export type UpsertRagDocumentParams = __Infer<typeof UpsertRagDocumentReducer>;
export type UpsertRagNormativeParams = __Infer<typeof UpsertRagNormativeReducer>;
export type UpsertResendConfigParams = __Infer<typeof UpsertResendConfigReducer>;
export type UpsertSystemSettingParams = __Infer<typeof UpsertSystemSettingReducer>;

